apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-back
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Aquí SÍ va la magia para limpiar la URL
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - unlucoin.info
      secretName: frontend-tls
  rules:
    - host: unlucoin.info
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-services
                port:
                  number: 8000