apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-back
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Aquí SÍ va la magia para limpiar la URL
    nginx.ingress.kubernetes.io/use-regex: "true"

    # --- OPTIMIZACIÓN DE VELOCIDAD ---
    # Mantiene la conexión abierta con el backend
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    # Aumenta los tiempos de espera para que no corte conexiones lentas
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - unlucoin.info
      secretName: frontend-tls
  rules:
    - host: unlucoin.info
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-services
                port:
                  number: 8000